#!/usr/bin/sh

# ------------------------------------------------
# Usage: gitproj [option] [repo name]
#
#     -h, --help               show help text
#     -p, --private            make repo private   
#
# Create github repo with current name
# Written by Ryan Corpuz
# ------------------------------------------------

package=gitproj
proj_path=.
. secret

# checks for input variable
if [ -z $1 ]; then
	echo "gitproj: missing operand"
	exit 1
fi

while test $# -gt 0; do
	case "$1" in
		-h|--help)
			echo "Usage: gitproj [OPTION] [REPO NAME]"
			echo "$package - create github repo"
			echo " "
			echo "$package [options] projectname"
			echo " "
			echo "options:"
			echo "-h, --help			show brief help"
      		echo "-p, --private			set repo to be private"
      		exit 0
      		;;
		-p|--private)
			shift
    	  	if test $# -gt 0; then
				local=$1
				curl -H "Authorization: token $GIT_API_TOKEN" https://api.github.com/user/repos -d '{"name": "'"${local}"'", "private": "true"}'
    	  	else
				echo "no name specified"
    	  	  	exit 1
    	  	fi
    	  	shift
    	  	;;
    	*)
			local=$1
			curl -H "Authorization: token $GIT_API_TOKEN" https://api.github.com/user/repos -d '{"name": "'"${local}"'"}'
			break
    	  	;;
	esac
done

mkcd () {
	mkdir "$1" && cd "$1"
}


mkcd "$local"
touch README.rst

### Creation of README.rst
cat <<EOF > README.rst
${local}
========

:Author:	$AUTHOR
:Source:	https://github.com/$GIT_USERNAME/$local
:Version: 
One paragraph of project description goes here

Installation
------------

Instructions
What things you need to install

'''
Give examples
'''

Usage
-----

A Step by step series of examples
Say what the step will be

'''
Give the example
'''

And repeat

'''
until finished
'''

End with an ex of getting some data out of the system or using it for a little demo
EOF

# Initializes local git and adds this to remote repo just created
git init
git add .
git commit -m "first commit"
git remote add origin https://${GIT_USERNAME}@github.com/${GIT_USERNAME}/${local}.git
git push -u origin master
